### ISSUE TITLE
--merge-output-format

### ISSUE THREAD

**Issue by superpowermanyob** [yausername/youtubedl-lazy#2]
hello~
                        request.addOption("-f", "bestvideo+bestaudio");
                        request.addOption("--merge-output-format", "mkv");
This file is created by separating mp3, mp4 sound and video.
this is working before.
why I don't konw. 
maybe it's problem youtubedl binay data or ffmpeg.

**Comment by xibr** [comment]
Your issue should be here [https://github.com/yausername/youtubedl-android/issues](https://github.com/yausername/youtubedl-android/issues)

**Comment by yausername** [comment]
@jungyoungsoo I am closing this. If you are still facing issues create one at https://github.com/yausername/youtubedl-android/issues
