### ISSUE TITLE
The latest version of youtube-dl cannot be used due to an error

### ISSUE THREAD

**Issue by xibr** [yausername/youtubedl-lazy#7]
hey @yausername, In the last update there is an error when using [youtubedl-android](https://github.com/yausername/youtubedl-android)
```
Traceback (most recent call last):
File "/data/user/0/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/__main__.py", line 19, in <module>
youtube_dl.main()
File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/__init__.py", line 475, in main
_real_main(argv)
File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/__init__.py", line 465, in _real_main
retcode = ydl.download(all_urls)
File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/YoutubeDL.py", line 2059, in download
res = self.extract_info(
File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/YoutubeDL.py", line 791, in extract_info
if not ie.suitable(url):
File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/lazy_extractors.py", line 2085, in suitable
return False if YoutubeIE.suitable(url) else super(
File "/data/data/com.yausername.youtubedl_android_example/no_backup/youtubedl-android/youtube-dl/youtube_dl/extractor/lazy_extractors.py", line 5612, in suitable
qs = parse_qs(url)
NameError: name 'parse_qs' is not defined

```
When building youtube-dl manually there is no such error.
I don't know the reason, but I think the problem is in this line [https://github.com/yausername/youtubedl-lazy/blob/950f9cadc6100d98a473d58335fa5bf90eb1c464/release.sh#L116](https://github.com/yausername/youtubedl-lazy/blob/950f9cadc6100d98a473d58335fa5bf90eb1c464/release.sh#L116) 
You can leave it as a comment and rebuild youtube-dl. You will not see the previous error when using it.

**Comment by CookieJarApps** [comment]
Importing `compat_parse_qs` from compat.py and replacing `parse_qs` with `compat_parse_qs` in the `lazy_extractors` file fixes the issue and downloads videos correctly. It seems to have been caused by [this ](https://github.com/ytdl-org/youtube-dl/commit/06159135ef148a6ddc632d0c89b90c937d5bb021#diff-0f24619cf9483f3bea670bba396939af35ea780edba90bb9d96ab20aae43386f) commit at youtube_dl. The `suitable` function has been changed to require `parse_qs`, which is defined elsewhere in the file. The  `suitable` function is added to the lazy_extractors file by the script in release.sh, but not the `parse_qs` function.

**Comment by mohad12211** [comment]
same issue here, I can't use youtubedl-android because of this. but I didn't understand @CookieJarApps 's fix, where can I find the `lazy_extractors` file and how can I use this in my android app? I'm kind of a beginner at android stuff :| 
or shall I just wait for a fix?

**Comment by CookieJarApps** [comment]
> same issue here, I can't use youtubedl-android because of this. but I didn't understand @CookieJarApps 's fix, where can I find the `lazy_extractors` file and how can I use this in my android app? I'm kind of a beginner at android stuff :| 
> or shall I just wait for a fix?

Basically, the version of youtube-dl bundled into youtubedl-android no longer works with YouTube, and if you update the youtube-dl version in the library, it updates to the broken version in this repo, which is missing a function and import in the lazy_extractors.py file. 

The lazy_extractors.py file is generated by this project and added to a zip with the rest of the youtube-dl files as releases ('youtube_dl.zip' in releases) in this repo every time there's an update in the youtube-dl repo. When the youtubedl-android library updates, this zip file is what it downloads.

I took the latest version of the file from this repo, and added the missing code to the lazy_extractors.py. The zip file is here: https://github.com/CookieJarApps/VideoDL/blob/master/app/src/main/res/raw/youtube_dl.zip 

Putting it into the /res/raw/ folder of your youtubedl-android project will override the built-in version in the library and (as long as you don't let the user update youtube-dl within the app) will act as a temporary fix until either youtube-dl or the author of this repo fixes the issue.

**Comment by xibr** [comment]
> defined elsewhere in the file. The `suitable` function is added to the lazy_extractors file by the script in release.sh, but not the `parse_qs` function.

Yes that's right.



> same issue here, I can't use youtubedl-android because of this. but I didn't understand @CookieJarApps 's fix, where can I find the `lazy_extractors` file and how can I use this in my android app? I'm kind of a beginner at android stuff :|
> or shall I just wait for a fix?

Like @CookieJarApps he said in the comment above.

For me I've built youtube-dl manually and it works for me without any problem, also check my [fork](https://github.com/xibr/youtubedl-lazy) [https://github.com/xibr/youtubedl-lazy/releases/tag/2021.04.17](https://github.com/xibr/youtubedl-lazy/releases/tag/2021.04.17) is built without lazy_extractors.py file and it works.

**Comment by xibr** [comment]
Anyone can make a fork and modify some lines in [youtubedl-lazy](https://github.com/yausername/youtubedl-lazy) and [youtubedl-android](https://github.com/yausername/youtubedl-android)
