### ISSUE TITLE
Re-enable lazy extractors

### ISSUE THREAD

**Issue by xibr** [yausername/youtubedl-lazy#9]
Do we have to Re-enable lazy extractors?
See [https://github.com/ytdl-org/youtube-dl/issues/28780](https://github.com/ytdl-org/youtube-dl/issues/28780)
Please take a look at these two commitments [https://github.com/ytdl-org/youtube-dl/commit/32290307a45260885b2210aa3c2a57e64abf8c34](https://github.com/ytdl-org/youtube-dl/commit/32290307a45260885b2210aa3c2a57e64abf8c34) [https://github.com/ytdl-org/youtube-dl/commit/c4a451b](https://github.com/ytdl-org/youtube-dl/commit/c4a451b)

Also i have tested it and it works [https://github.com/xibr/youtubedl-lazy/releases/tag/2021.04.26](https://github.com/xibr/youtubedl-lazy/releases/tag/2021.04.26)

@yausername Can you take a look at this when you have time?

**Comment by yausername** [comment]
I had found using lazy extractors to be little faster in loading the video info.
If youtube-dl have fixed the issue, we can enable it back.

**Comment by xibr** [comment]
Yes, they fixed it, i tested it on YouTube and it works without any problems, I will make sure that there is no problem with other sites and then I will open a pull request.
